/*

 OVERWORLDMB.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 60 x 37
   Tile set      : C:\Users\7319a\Documents\Programming\GameBoy\Projects\game-Boy-Action-Adventure-Template\assets\game Boy Tile Designer\overworldTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 51
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __overworldMB_h_INCLUDE
#define __overworldMB_h_INCLUDE

#define overworldMapWidth 60
#define overworldMapHeight 37
#define overworldMapBank 0

extern const unsigned char overworldMap[];

#endif

/* End of OVERWORLDMB.H */
